export const defaultSites = [
  {
    id: "bitcoin-dashboard",
    name: "比特币投资仪表盘",
    description: "聚合链上估值、周期风险与市场时段指标，辅助判断比特币所处的位置。",
    url: "https://bitcoin-investment-dashboard.vercel.app/",
    color: "#e58a17",
    favicon: "https://bitcoin-investment-dashboard.vercel.app/favicon.svg",
  },
  {
    id: "company-research",
    name: "公司深度调研档案",
    description: "从产品、商业模式、财务质量到估值情景，沉淀持续更新的公司研究。",
    url: "https://company-research-archive.netlify.app/",
    color: "#15936f",
    favicon: "https://company-research-archive.netlify.app/favicon.ico",
  },
  {
    id: "research-report-atlas",
    name: "研究报告精读库",
    description: "汇集研究报告的卡片式精读版本，方便回看、比较并继续深入阅读。",
    url: "https://research-report-atlas.netlify.app/",
    color: "#0d6b78",
    favicon: "https://research-report-atlas.netlify.app/favicon.ico",
  },
  {
    id: "ai22-source-navigator",
    name: "AI 22人一手资料导航",
    description: "持续追踪 22 位重要 AI 人物的论文、文章、演讲、访谈与官方来源。",
    url: "https://ai22-source-navigator.netlify.app/",
    color: "#1768e5",
    favicon: "https://ai22-source-navigator.netlify.app/favicon.svg",
  },
  {
    id: "gx-tweets",
    name: "GX 推文研究库",
    description: "汇集 AI 相关推文、标签与分析报告，方便浏览和回溯重点观点。",
    url: "https://gx.yz.rs/",
    color: "#1768e5",
    favicon: "https://gx.yz.rs/favicon.ico",
  },
  {
    id: "ai-kol",
    name: "AI KOL 推文库",
    description: "追踪 AI 领域关键意见领袖的推文，并按标签和报告沉淀研究线索。",
    url: "https://aikol.yz.rs/",
    color: "#7357c8",
    favicon: "https://aikol.yz.rs/favicon.ico",
  },
  {
    id: "podcast-research",
    name: "播客研究库",
    description: "整理长播客的论点摘要、嘉宾信息、原文转录与深度研究内容。",
    url: "https://podcast-research-iota.vercel.app/podcast-research.html",
    color: "#db5b3d",
    favicon: "https://podcast-research-iota.vercel.app/favicon.ico",
  },
  {
    id: "paper-vault",
    name: "BVC 论文档案",
    description: "集中收藏、检索和阅读 BVC 相关论文与研究资料。",
    url: "https://bvclibrary.zheshi.tech/paper-vault-bv/",
    color: "#15936f",
    favicon: "https://bvclibrary.zheshi.tech/favicon.ico",
  },
  {
    id: "bvc-portal",
    name: "BVC 社区门户",
    description: "进入 BVC 社区服务与内容空间的统一入口。",
    url: "https://bvcportal.com/",
    color: "#d89311",
    favicon: "https://bvcportal.com/favicon.ico",
  },
];
